language: go

sudo: false

before_script:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - export PATH=$PATH:bats/bin
  - go get golang.org/x/tools/cmd/cover

go:
  - 1.5
  - tip

install:
  - go get -t

matrix:
  allow_failures:
    - go: tip

before_deploy:
  - go get github.com/mitchellh/gox
  - gox

deploy:
  provider: releases
  api_key:
    secure: SUBoX5zAsRLYshfpmK1aeVWMU7ZMnpVNa9YqDi4QP95iNhuw28Dhl5uqORoGnog4AhN8X3cdJTOYB0QA7nboBvm+OytDaHCOpzV5CNHVrQ/fjMZmsgQW0UoweWjDUWtlDHSpMa3XywAoVkGxLEp9hAWom/MIWVAOOWueuKEYxCo=
  file:
    - emoji-weather_darwin_386
    - emoji-weather_darwin_amd64
    - emoji-weather_freebsd_386
    - emoji-weather_freebsd_amd64
    - emoji-weather_freebsd_arm
    - emoji-weather_linux_386
    - emoji-weather_linux_amd64
    - emoji-weather_linux_arm
    - emoji-weather_netbsd_386
    - emoji-weather_netbsd_amd64
    - emoji-weather_netbsd_arm
    - emoji-weather_openbsd_386
    - emoji-weather_openbsd_amd64
    - emoji-weather_windows_386.exe
    - emoji-weather_windows_amd64.exe
  skip_cleanup: true
  on:
    repo: justincampbell/emoji-weather
    tags: true
